### ISSUE TITLE
error on running "[ROOP.CORE] ffmpeg is not installed."

### ISSUE THREAD

**Issue by davad00** [based9based/roop#4]
## Description

A concise description of the bug and how to reproduce it.

installed everything as needed and when i try to run the sofware it outputs this 
"
[ROOP.CORE] ffmpeg is not installed.
"
i did pip install ffmpeg after that and it gave the same output..
## Error

Paste the error or exception from your console:

```
[ROOP.CORE] ffmpeg is not installed.
```

## Details

What operating system are you using?

- [ ] Windows 10 64bit

What execution provider are you using?

- [ ] CUDA

What version of Roop are you using?

- [ ] 1.3.2

**Comment by mehtaabGill** [comment]
+1 on this. Also facing this issue on windows 11. Issue persists after installing ffmpeg manually.

```
[ROOP.CORE] ffmpeg is not installed.
Traceback (most recent call last):
  File "C:\Users\mehta\Downloads\roop-main (1)\roop-main\run.py", line 6, in <module>
    core.run()
  File "C:\Users\mehta\Downloads\roop-main (1)\roop-main\roop\core.py", line 210, in run
    if not pre_check():
           ^^^^^^^^^^^
  File "C:\Users\mehta\Downloads\roop-main (1)\roop-main\roop\core.py", line 120, in pre_check
    update_status('ffmpeg is not installed.')
  File "C:\Users\mehta\Downloads\roop-main (1)\roop-main\roop\core.py", line 128, in update_status
    ui.update_status(message)
  File "C:\Users\mehta\Downloads\roop-main (1)\roop-main\roop\ui.py", line 143, in update_status
    status_label.configure(text=text)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'configure'
```

**Comment by Anonymous7860** [comment]
change runtime to t4 or tpu

**Comment by davad00** [comment]
> 
??
we run it localy on our pc not on google colab

**Comment by 07dav07** [comment]
davad00 same problem in windows11 and solved whit          winget install "FFmpeg (Essentials Build)"      from cmd.
however openvino doens't work only cpu option. 
commands are wrong
python run.py -t ./content/vid1.mp4 -s ./content/image8.png -o ./content/swapped.mp4 --execution-provider cpu --frame-processor face_swapper face_enhancer 
this work.

**Comment by Anonymous7860** [comment]
or copy the locations of files after -t  and -s .

**Comment by downysoftware** [comment]
Installing "FFmpeg (Essentials Build)" with winget changed nothing for me.

**Comment by yuanshuo1022** [comment]
Solution: After downloading FFmpeg, you need to set environment variables and restart. To set the bin file under ffmpeg to the environment variable, run the ffmpeg command in cmd to check whether it takes effect.
![Uploading Snipaste_2024-07-06_07-19-04.png…]()
